### PR TITLE
Force remove microsoft edge regardless of region/country.

### PR DESCRIPTION
**Pull request by loadstring1**
Tested and works on my windows 11 home 22h2 it wiped microsoft edge out of my system. I used closed-source programs to help myself with writing this feature.

**Please let me know if i should also consider force uninstalling edge webview and edge update because for now this is just edge uninstaller**

fixes this issue: [38](https://github.com/Raphire/Win11Debloat/issues/38)

### CODE REVIEW

**Comment by loadstring1** [comment]
microsoft edge update is now removed alongside with microsoft edge

it doesn't uninstall edge webview because you can manually uninstall it so automatic script is not really needed for that also edge webview is required for roblox studio to work so its a big adventage for people who play roblox (like me) 

:)

**Comment by loadstring1** [comment]
one more thing if you are wondering how to test if it works correctly and you don't have edge installed

then download edge and install it from here or just install ms edge with winget: https://www.microsoft.com/en-us/edge/download?form=MA13FJ

**Comment by zoicware** [comment]
i have modified an existing script from @AveYo to completely uninstall edge (webview hard locked cant uninstall anymore)
(Notice making a folder and exe fixes it from being unable to be uninstalled OG Script: https://github.com/AveYo/fox/blob/main/Edge_Removal.bat)

**Comment by loadstring1** [comment]
> I have modified an existing script from @AveYo to completely uninstall edge (webview hard locked cant uninstall anymore) OG Script: https://github.com/AveYo/fox/blob/main/Edge_Removal.bat) My edited script (Notice making a folder and exe fixes it from being unable to be uninstalled): [EdgeRemove.zip](https://github.com/user-attachments/files/15527337/EdgeRemove.zip)

your script looks way more advanced than mine maybe make seperate pull request for that?

**Comment by zoicware** [comment]
> > I have modified an existing script from @AveYo to completely uninstall edge (webview hard locked cant uninstall anymore) OG Script: https://github.com/AveYo/fox/blob/main/Edge_Removal.bat) My edited script (Notice making a folder and exe fixes it from being unable to be uninstalled): [EdgeRemove.zip](https://github.com/user-attachments/files/15527337/EdgeRemove.zip)
> 
> your script looks way more advanced than mine maybe make seperate pull request for that?

https://github.com/Raphire/Win11Debloat/pull/66 
went ahead and replaced onedrive removal as well

**Comment by loadstring1** [comment]
> #66 went ahead and replaced onedrive removal as well

onedrive actually uninstalls without refusing to do that so you don't have to force uninstall it

**Comment by Raphire** [comment]
I will have a look at this soon. Although I'm not sure how I feel about manually removing everything related to edge like this. It can become a pain if anything related to registry or location of stored files changes in the future.

**Comment by loadstring1** [comment]
> I will have a look at this soon. Although I'm not sure how I feel about manually removing everything related to edge like this. It can become a pain if anything related to registry or location of stored files changes in the future.

You can't just rely on registry to disable windows features

about Microsoft Edge:
A) It's piece of bloatware wasting around 700 MB of disk space
B) There is no other way of removing microsoft edge other than force killing all of its processes and deleting it from Program Files x86 and auto start
C) uninstall.exe method got patched and it doesn't uninstall itself anymore you really need to forcefully uninstall it like that (aka it ignores anything that tries to uninstall msedge that way)

or finally just wait until microsoft actually allows you to uninstall msedge without refusing to do that (obviously they won't allow you to uninstall their "best browser" just because of this github repo)

What i learned is MSedge reinstalls itself by relying on edge update "service" booting on start-up in task scheduler and registry auto start so my pull request targets both microsoft edge and edge update so it doesn't reinstall itself

I still can't disagree this script looks pretty messy and it requires constant updating when microsoft moves their browser somewhere else (for example migration from program files x86 to program files you get what i mean)


Registry key removal is pretty messy and maybe i'll try fixing that mess

**Comment by loadstring1** [comment]
> Registry key removal is pretty messy and maybe i'll try fixing that mess

- registry mess fixed
- merged with latest win11debloat master branch

**Comment by loadstring1** [comment]
keeping this up-to-date so you can merge it without conflicts in the future

**Comment by Raphire** [comment]
@loadstring1 I like the way you implemented this, but the method recently mentioned in #38 is a bit cleaner and utilizes the installer to do most of the heavy lifting. I have adapted this method and included some of your tricks aswell here: https://github.com/Raphire/Win11Debloat/tree/EdgeRemove-experimental

P.S. I opted not to remove EdgeCore and EdgeUpdate. Removing EdgeCore seems to break Widgets, and may also break other OS functionality. Removing EdgeUpdate may cause Webview2 to not update anymore at all, which could pose security issues and/or cause certain apps that require Webview2 to not work at all.

**Comment by loadstring1** [comment]
> @loadstring1 I like the way you implemented this, but the method recently mentioned in #38 is a bit cleaner and utilizes the installer to do most of the heavy lifting.

Thank you

> P.S. I opted not to remove EdgeCore and EdgeUpdate. Removing EdgeCore seems to break Widgets, and may also break other OS functionality. Removing EdgeUpdate may cause Webview2 to not update anymore at all, which could pose security issues and/or cause certain apps that require Webview2 to not work at all.

My script deletes those two because i don't really care about widgets i don't use that feature myself

but good catch i didn't notice anything because i don't use widgets at all

**Comment by Raphire** [comment]
Closing PR (See: https://github.com/Raphire/Win11Debloat/pull/64#issuecomment-2190121090)

**Pull request closed without merging**
